import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/1743746125/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:390,height:844}});
page.on('pageerror',e=>console.log('PAGE ERROR:',e.message));
page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE:',m.text());});
await page.route('**/*.js',route=>route.abort());
await page.route('https://**/*',route=>route.abort());
await page.goto('http://localhost:4174',{waitUntil:'domcontentloaded'});
console.log('button handler:',await page.locator('#open').evaluate(e=>typeof e.onclick));
await page.locator('#open').click();
await page.waitForTimeout(1000);
console.log('book visible:',await page.locator('#book').isVisible());
if(!await page.locator('#book').isVisible())throw Error('拆信失败');
await page.locator('.wish').first().click();
if(await page.locator('.wish').first().getAttribute('aria-pressed')!=='true')throw Error('翻卡失败');
await page.locator('.polaroid').first().click();
if(!await page.locator('#photo-dialog').isVisible())throw Error('相册失败');
await page.locator('#close-photo').click();
await page.locator('#gesture').click();
if(!await page.locator('#camera-panel').isVisible())throw Error('手势面板失败');
await page.locator('#blow').click();
await page.locator('#reset').waitFor({state:'visible'});
if(!(await page.locator('#cake-scene').getAttribute('class')).includes('blown'))throw Error('蜡烛失败');
await page.locator('#reset').click();
await page.locator('#coupon-button').click();
if(!await page.locator('#coupon').isVisible())throw Error('彩蛋失败');
await page.goto(new URL('../dist/index.html',import.meta.url).href,{waitUntil:'domcontentloaded'});
await page.locator('#open').click();
await page.locator('#book').waitFor({state:'visible'});
console.log('PASS: 外部脚本全部被阻断时，拆信、翻卡、相册、吹蜡烛、重置、彩蛋可用；双击 HTML 也可拆信。');
await browser.close();

